export const GET_ADMIN = 'GET_ADMIN'
export const POST_ADMIN = 'POST_ADMIN'
export const GET_PRODUCTS = 'GET_PRODUCTS'
export const POST_PRODUCT = 'POST_PRODUCT'
export const GET_USERS = 'GET_USERS'
export const GET_USER = 'GET_USER'
export const GET_CATEGORIES = 'GET_CATEGORIES'
